-- =========================================================
-- ROBOTEROIDS – GEMEINSAME KLASSEN-HIGHSCORELISTE
-- Supabase: SQL Editor -> New query -> alles einfügen -> Run
-- =========================================================

create table if not exists public.roboteroids_scores (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    nickname text not null,
    score integer not null default 0,
    level integer not null default 1,
    duration_seconds integer not null default 0,
    game_version text not null default 'roboteroids_v1',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_submitted_at timestamptz not null default now(),
    constraint roboteroids_nickname_length check (char_length(nickname) between 1 and 16),
    constraint roboteroids_score_range check (score between 0 and 50000),
    constraint roboteroids_level_range check (level between 1 and 30),
    constraint roboteroids_duration_range check (duration_seconds between 0 and 180),
    constraint roboteroids_unique_player_name unique (user_id, nickname, game_version)
);

alter table public.roboteroids_scores enable row level security;
revoke all on table public.roboteroids_scores from anon, authenticated;

drop function if exists public.submit_roboteroids_score(text, integer, integer, integer);
drop function if exists public.get_roboteroids_leaderboard();

create function public.submit_roboteroids_score(
    p_nickname text,
    p_score integer,
    p_level integer,
    p_duration_seconds integer
)
returns table (
    best_score integer,
    improved boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user uuid;
    v_name text;
    v_old integer;
begin
    v_user := auth.uid();

    if v_user is null then
        raise exception 'Nicht angemeldet';
    end if;

    v_name := trim(regexp_replace(coalesce(p_nickname, ''), '\s+', ' ', 'g'));

    if char_length(v_name) < 1 or char_length(v_name) > 16 then
        raise exception 'Nickname muss 1 bis 16 Zeichen lang sein';
    end if;

    if v_name ~ '[[:cntrl:]]' then
        raise exception 'Nickname enthält unzulässige Zeichen';
    end if;

    if p_score < 0 or p_score > 50000 then
        raise exception 'Punktzahl außerhalb des erlaubten Bereichs';
    end if;

    if p_level < 1 or p_level > 30 then
        raise exception 'Level außerhalb des erlaubten Bereichs';
    end if;

    if p_duration_seconds < 0 or p_duration_seconds > 180 then
        raise exception 'Spieldauer außerhalb des erlaubten Bereichs';
    end if;

    if exists (
        select 1
        from public.roboteroids_scores r
        where r.user_id = v_user
          and lower(r.nickname) = lower(v_name)
          and r.game_version = 'roboteroids_v1'
          and r.last_submitted_at > now() - interval '5 seconds'
    ) then
        raise exception 'Bitte kurz warten, bevor du erneut speicherst';
    end if;

    select r.score
      into v_old
      from public.roboteroids_scores r
     where r.user_id = v_user
       and lower(r.nickname) = lower(v_name)
       and r.game_version = 'roboteroids_v1'
     limit 1;

    insert into public.roboteroids_scores (
        user_id, nickname, score, level, duration_seconds,
        game_version, created_at, updated_at, last_submitted_at
    )
    values (
        v_user, v_name, p_score, p_level, p_duration_seconds,
        'roboteroids_v1', now(), now(), now()
    )
    on conflict (user_id, nickname, game_version)
    do update set
        score = greatest(public.roboteroids_scores.score, excluded.score),
        level = case
            when excluded.score > public.roboteroids_scores.score then excluded.level
            else public.roboteroids_scores.level
        end,
        duration_seconds = case
            when excluded.score > public.roboteroids_scores.score then excluded.duration_seconds
            else public.roboteroids_scores.duration_seconds
        end,
        updated_at = case
            when excluded.score > public.roboteroids_scores.score then now()
            else public.roboteroids_scores.updated_at
        end,
        last_submitted_at = now();

    return query
    select r.score,
           (v_old is null or p_score > v_old)
      from public.roboteroids_scores r
     where r.user_id = v_user
       and lower(r.nickname) = lower(v_name)
       and r.game_version = 'roboteroids_v1'
     limit 1;
end;
$$;

create function public.get_roboteroids_leaderboard()
returns table (
    nickname text,
    score integer,
    level integer,
    updated_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
    select x.nickname, x.score, x.level, x.updated_at
    from (
        select distinct on (lower(r.nickname))
               r.nickname, r.score, r.level, r.updated_at
          from public.roboteroids_scores r
         where r.game_version = 'roboteroids_v1'
         order by lower(r.nickname), r.score desc, r.updated_at asc
    ) x
    order by x.score desc, x.updated_at asc
    limit 15;
$$;

revoke execute on function public.submit_roboteroids_score(text, integer, integer, integer)
from public, anon;

revoke execute on function public.get_roboteroids_leaderboard()
from public, anon;

grant execute on function public.submit_roboteroids_score(text, integer, integer, integer)
to authenticated;

grant execute on function public.get_roboteroids_leaderboard()
to authenticated;
